[package]
edition = "2021"
name = "rglk"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.8"
bit-set = "0.5.3"
bracket-bevy = {git = "https://github.com/amethyst/bracket-lib"}
bracket-lib = "0.8"
